name: KeinShin

on:
  push:
    branches:
    - rebith


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "chat_id"

          replace: "chat.id"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Stuffs'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: Kei

          commit_user_email: poxsisofficial@gmail.com
